"""empty message

Revision ID: 948fb72fd170
Revises: 799353f349fc
Create Date: 2019-03-13 09:23:40.292912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948fb72fd170'
down_revision = '799353f349fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('futcontract', sa.Column('ctrf_month', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'futcontract', 'month_c', ['ctrf_month'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'futcontract', type_='foreignkey')
    op.drop_column('futcontract', 'ctrf_month')
    # ### end Alembic commands ###
