"""empty message

Revision ID: baf38df78d93
Revises: 
Create Date: 2019-03-13 08:58:50.300692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf38df78d93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greeksopt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delta_put', sa.Float(precision=10), nullable=False),
    sa.Column('delta_call', sa.Float(precision=10), nullable=False),
    sa.Column('gamma_put', sa.Float(precision=10), nullable=False),
    sa.Column('gamma_call', sa.Float(precision=10), nullable=False),
    sa.Column('theta_put', sa.Float(precision=10), nullable=False),
    sa.Column('theta_call', sa.Float(precision=10), nullable=False),
    sa.Column('vega_put', sa.Float(precision=10), nullable=False),
    sa.Column('vega_call', sa.Float(precision=10), nullable=False),
    sa.Column('rho_put', sa.Float(precision=10), nullable=False),
    sa.Column('rho_call', sa.Float(precision=10), nullable=False),
    sa.Column('opt_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opt_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greeksopt')
    # ### end Alembic commands ###
